version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019 Preview
configuration: Release
before_build:
- cmd: dotnet restore
build:
  project: src\Parbad\Parbad.csproj
  publish_nuget: true
  verbosity: minimal
deploy: off