version: 1.0.{build}
image: Visual Studio 2019 Preview
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: src\Parbad\Parbad.csproj
  publish_nuget: true
  verbosity: minimal
deploy: off