trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'release'

stages:
  - stage: Development
    condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
    jobs:
    - job: Initializing
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'restoring'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'building'
        inputs:
          command: 'build'
          projects: 'src/**/*.csproj'
          arguments: '-c $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'packing'
        inputs:
          command: 'custom'
          projects: 'src/**/*.csproj'
          custom: 'pack'
          arguments: '-c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)/packages/prereleases --version-suffix dev$(Build.BuildNumber)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/packages/prereleases'
          ArtifactName: 'prereleases'
          publishLocation: 'Container'
  - stage: Production
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
    jobs:
    - job: Initializing
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'restoring'
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'building'
        inputs:
          command: 'build'
          projects: 'src/**/*.csproj'
          arguments: '-c $(buildConfiguration)'
      - task: DotNetCoreCLI@2
        displayName: 'packing'
        inputs:
          command: 'custom'
          projects: 'src/**/*.csproj'
          custom: 'pack'
          arguments: '-c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)/packages/releases'
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '>=4.x'
          checkLatest: true
      - script: nuget push -ApiKey $(ApiKey) -Source "https://api.nuget.org/v3/index.json" $(Build.ArtifactStagingDirectory)/packages/releases/*.nupkg