trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '-c $(buildCOnfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'src/**/*.csproj;!**/*.Tests.csproj'
    custom: 'dotnet pack'
    arguments: '-c $(buildConfiguration) --no-build --skip-duplicate'
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '69c14a16-aa9b-4eb1-b20b-f8084e16add5/80283fdf-ec52-4bc8-944d-14c8f4f6c49c'
