trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'
    arguments: '-c $(buildCOnfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    projects: 'src/**/*.csproj'
    custom: 'pack'
    arguments: '-c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '279df34c-5022-41d4-b4c9-079b9ee673d2/079abce9-be4c-41d8-8897-5fcf6b8465d0'